import {Fragment} from 'react'
import {Box,Heading,Text,Container} from '@chakra-ui/react'
import Head from 'next/head'



export default function AboutUs() {
  return (
      <Fragment>
      <Head>
        <title>About Us | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      

        <Container>
          <Heading
            as="h1"
            variant="h1"
            color="basic.5"
            textAlign={{ base: "center", md: "left" }}
          >
            About Us
          </Heading>
          <Text color="basic.5" textAlign={{ base: "center", md: "left" }}>
            Lorem100    
          </Text>
        </Container>

      </Fragment>
  )
}
